from decimal import Decimal
from django.db import models
class Comprobante(models.Model):
    ESTADOS=[('BORRADOR','Borrador'),('FIRMADO','Firmado'),('RECIBIDA','Recibida'),('AUTORIZADO','Autorizado'),('NO_AUTORIZADO','No autorizado')]
    TIPOS=[('01','Factura'),('03','Liquidación de compra'),('04','Nota de crédito'),('05','Nota de débito'),('06','Guía de remisión'),('07','Retención')]
    tipo=models.CharField(max_length=2,choices=TIPOS,default='01'); fecha_emision=models.DateField(); establecimiento=models.CharField(max_length=3,default='001'); punto_emision=models.CharField(max_length=3,default='001'); secuencial=models.PositiveIntegerField(); clave_acceso=models.CharField(max_length=49,unique=True,blank=True); estado=models.CharField(max_length=20,choices=ESTADOS,default='BORRADOR'); cliente=models.ForeignKey('clientes.Cliente',on_delete=models.PROTECT,related_name='comprobantes'); subtotal=models.DecimalField(max_digits=14,decimal_places=2,default=Decimal('0')); descuento=models.DecimalField(max_digits=14,decimal_places=2,default=Decimal('0')); iva=models.DecimalField(max_digits=14,decimal_places=2,default=Decimal('0')); total=models.DecimalField(max_digits=14,decimal_places=2,default=Decimal('0')); xml_generado=models.TextField(blank=True); xml_firmado=models.TextField(blank=True); xml_autorizado=models.TextField(blank=True); numero_autorizacion=models.CharField(max_length=49,blank=True); mensaje_sri=models.TextField(blank=True); creado=models.DateTimeField(auto_now_add=True); actualizado=models.DateTimeField(auto_now=True)
    class Meta: constraints=[models.UniqueConstraint(fields=['tipo','establecimiento','punto_emision','secuencial'],name='uq_comprobante_numero')]
class DetalleComprobante(models.Model):
    comprobante=models.ForeignKey(Comprobante,on_delete=models.CASCADE,related_name='detalles'); producto=models.ForeignKey('productos.Producto',on_delete=models.PROTECT); codigo=models.CharField(max_length=50); descripcion=models.CharField(max_length=300); cantidad=models.DecimalField(max_digits=14,decimal_places=4); precio_unitario=models.DecimalField(max_digits=14,decimal_places=4); descuento=models.DecimalField(max_digits=14,decimal_places=2,default=Decimal('0')); subtotal=models.DecimalField(max_digits=14,decimal_places=2,default=Decimal('0')); iva=models.DecimalField(max_digits=14,decimal_places=2,default=Decimal('0')); total=models.DecimalField(max_digits=14,decimal_places=2,default=Decimal('0'))
class Pago(models.Model):
    FORMAS=[('01','Sin utilización del sistema financiero'),('16','Tarjeta de débito'),('19','Tarjeta de crédito'),('20','Otros con utilización del sistema financiero')]
    comprobante=models.ForeignKey(Comprobante,on_delete=models.CASCADE,related_name='pagos'); forma_pago=models.CharField(max_length=2,choices=FORMAS,default='20'); total=models.DecimalField(max_digits=14,decimal_places=2); plazo=models.PositiveIntegerField(default=0); unidad_tiempo=models.CharField(max_length=20,default='dias')
